"""Terminal color codes for Zepton."""
class Colors:
    RED     = "\033[91m"
    GREEN   = "\033[92m"
    YELLOW  = "\033[93m"
    BLUE    = "\033[94m"
    MAGENTA = "\033[95m"
    CYAN    = "\033[96m"
    WHITE   = "\033[97m"
    BOLD    = "\033[1m"
    DIM     = "\033[2m"
    UNDER   = "\033[4m"
    RESET   = "\033[0m"

def success(text):  return f"{Colors.GREEN}[+] {Colors.RESET}{text}"
def error(text):    return f"{Colors.RED}[-] {Colors.RESET}{text}"
def warning(text):  return f"{Colors.YELLOW}[!] {Colors.RESET}{text}"
def info(text):     return f"{Colors.CYAN}[*] {Colors.RESET}{text}"
def banner(text):   return f"{Colors.BOLD}{Colors.CYAN}{text}{Colors.RESET}"
  
